//
//  LocalizableGenerator.swift
//  GenerateLocalizables
//
//  Created by Jose Escabias on 24/10/21.
//  Copyright © 2021 Jose Escabias. All rights reserved.
//

import Foundation
import Files

class LocalizableGenerator {
    public static func createFile(for language: String, with localizables: [Localizable], destination: String) throws {
        var localizabeText = ""
        localizabeText = "// This Localizable file is Autogenerated with a script. Please don´t modify this file by hand \n"

        localizables.forEach { localizable in
            if localizable.key.isEmpty {
                localizabeText = localizabeText + "\n"
            } else  {
                let hasSlash = localizable.key.contains { char in
                    return char == "/"
                }
                if hasSlash {
                    localizabeText = localizabeText + localizable.key
                } else {
                    localizabeText = localizabeText + "\n" + "\"\(localizable.key)\"" + " = " + "\"\(localizable.value)\";"
                }
            }
        }

        do {
            let folder = Folder.current
            var file: File
            let subFolder = try folder.createSubfolderIfNeeded(at: destination)
            let languageFolder = try subFolder.createSubfolder(named: "\(language).lproj")
            try languageFolder.createFile(named: "Localizable.strings")
            file = try languageFolder.file(named: "Localizable.strings")
            try file.write(localizabeText)
            print("✅ Created \(languageFolder.path)".green)
        } catch  {
            print("❌ ERROR CREATING THE LOCALIZABLE STRING FILE ❌".red)
            exit(EXIT_FAILURE)
        }
    }
}
